[tool.poetry]
name = "tiny_pacs"
version = "0.2.0"
description = ""
authors = ["Pavel 'Blane' Tuchin <blane.public@gmail.com>"]
license = "MIT"
readme = "README.rst"
keywords = ["medical", "dicom", "network"]

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries"
]

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pydicom = "^3.0"
pynetdicom2 = "^0.9.8"
peewee = "^4.3"
PyYAML = "^6.0"
trolleybus = "^0.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^9.0"
ruff = "*"
mypy = "^1.0"

[tool.poetry.scripts]
tiny-pacs = "tiny_pacs.__main__:main"

[build-system]
requires = ["poetry-core>=2.0"]
build-backend = "poetry.core.masonry.api"
