"""Comment extraction and rendering for generated configuration YAML.

The generated configuration explains itself: this module derives every
comment from material that already exists — component class docstrings,
``:ivar:`` entries of the configuration models,
:attr:`pydantic.Field.description` and machine-checkable facts from the
model fields (enum values, numeric bounds, required/optional) — and
inserts them into the deterministic block-style output of
``yaml.safe_dump`` used by :func:`tiny_pacs.config.dump_yaml` (a line
post-pass; PyYAML itself cannot emit comments).

Extraction is defensive by design: a missing, broken or exotic docstring
degrades to "no comment" for that entry and never raises — the same
posture as :func:`tiny_pacs.config.load_component_plugins`. As a last
resort :func:`render_commented_yaml` verifies that the commented
document still parses into the same data and falls back to the plain
dump when it does not.

Serialization contract: the emitter assumes ``dump_yaml``'s settings
(``sort_keys=False``, ``default_flow_style=False``, block style only,
two-space indents). Comment insertion never modifies an existing line,
so value serialization stays byte-identical.
"""
import enum
import functools
import inspect
import logging
import re
import textwrap
import types
import typing
from typing import TYPE_CHECKING, Any

import pydantic
import yaml  # type: ignore[import-untyped]

from . import component

if TYPE_CHECKING:  # pragma: no cover
    from . import config

logger = logging.getLogger('tiny_pacs.config_comments')

#: Target width of rendered comment lines (indent + ``# `` + text)
COMMENT_WIDTH = 76

#: Banner printed at the top of every commented document
BANNER = (
    'Generated by "tiny-pacs config generate" — regenerate instead of '
    'hand-editing. Comments are generated from component and '
    'configuration model docstrings.'
)

#: Banner printed above the first non-built-in component entry
EXTENSION_BANNER = (
    'The components below are provided by installed extension packages '
    'and are off by default; set "on: true" to enable them.'
)

#: Fixed texts for sections that no pydantic model backs
_STATIC_COMMENTS: dict[tuple[str, ...], str] = {
    ('log',): (
        'Python logging configuration, passed to '
        'logging.config.dictConfig() — see the "Configuration dictionary '
        'schema" section of the Python logging documentation.'
    )
}

_SECRET_WARNING = (
    'Stored in plain text; the generated file is written with mode 0600.'
)

#: Credential fields receiving a canned warning, keyed by
#: ``(module, class qualname, field name)`` — opt-in, never guessed
#: from field names
_SECRET_FIELDS = {
    ('tiny_pacs.db', 'DatabaseConfig', 'password'),
    ('tiny_pacs.devices', 'DeviceConfig', 'password'),
}

_ROLE_RE = re.compile(r':[a-zA-Z][a-zA-Z0-9_.:+-]*:`([^`]*)`')
_LITERAL_RE = re.compile(r'``([^`]*)``')
_WHITESPACE_RE = re.compile(r'\s+')
_FIELD_MARKER_RE = re.compile(
    r':(ivar|var|cvar|param|type|returns?|rtype|raises|keyword)\b')
_IVAR_RE = re.compile(r':ivar\s+([A-Za-z_][\w.\-]*)\s*:\s*(.*)')
_PARAGRAPH_STOP_RE = re.compile(r'^(\*|-[ \t]|\.\.[ \t])')


def sanitize_text(text: str) -> str:
    """Strips reST markup down to plain prose.

    Cross-reference roles (``:class:``, ``:data:``, ``:func:``, ...) keep
    their title (or their target, shortened for ``~`` references), inline
    literals keep their text and whitespace is collapsed. YAML comments
    are plain prose; the docstrings they are extracted from are written
    for Sphinx.

    :param text: raw docstring fragment
    :type text: str
    :return: sanitized single-line text
    :rtype: str
    """

    def replace_role(match: re.Match[str]) -> str:
        return _role_target(match.group(1))

    text = _ROLE_RE.sub(replace_role, text)
    text = _LITERAL_RE.sub(r'\1', text)
    return _WHITESPACE_RE.sub(' ', text).strip()


def _role_target(inner: str) -> str:
    """Plain text of one role target (``title <target>`` / ``~dotted``)."""
    if '<' in inner and inner.rstrip().endswith('>'):
        return inner.split('<', 1)[0].strip()
    target = inner.strip()
    if target.startswith('~'):
        return target[1:].rsplit('.', 1)[-1]
    return target


@functools.cache
def parse_docstring(
        docstring: Any
) -> tuple[str, dict[str, str]]:
    """Splits a docstring into summary and ``:ivar:`` entries.

    The summary is the prose before the first field list, at most two
    paragraphs; a paragraph introducing a bulleted list ("Handles the
    following events:") and the list itself are dropped. ``:ivar:``
    entries include multi-line hanging continuations and are sanitized.
    The result is cached and shared — callers must not mutate the
    returned dict.

    :param docstring: raw docstring; anything non-string yields no result
    :return: ``(summary, {field name: sanitized text})``
    :rtype: tuple[str, dict[str, str]]
    """
    if not docstring or not isinstance(docstring, str):
        return '', {}
    try:
        lines = inspect.cleandoc(docstring).split('\n')
    except Exception:  # pragma: no cover - cleandoc is total on str
        return '', {}
    paragraphs: list[str] = []
    ivars: dict[str, str] = {}
    index = 0
    total = len(lines)
    while index < total:
        stripped = lines[index].strip()
        if not stripped:
            index += 1
            continue
        if _FIELD_MARKER_RE.match(stripped) or _PARAGRAPH_STOP_RE.match(
                stripped):
            match = _IVAR_RE.match(stripped)
            index += 1
            body: list[str] = []
            while index < total:
                continuation = lines[index].strip()
                if (not continuation
                        or _FIELD_MARKER_RE.match(continuation)
                        or _PARAGRAPH_STOP_RE.match(continuation)):
                    break
                body.append(continuation)
                index += 1
            if match is not None:
                text = sanitize_text(
                    ' '.join([match.group(2)] + body))
                if text:
                    ivars.setdefault(match.group(1), text)
            continue
        paragraph: list[str] = []
        while index < total:
            continuation = lines[index].strip()
            if (not continuation
                    or _FIELD_MARKER_RE.match(continuation)
                    or _PARAGRAPH_STOP_RE.match(continuation)):
                break
            paragraph.append(continuation)
            index += 1
        text = sanitize_text(' '.join(paragraph))
        if text:
            paragraphs.append(text)
    return _join_summary(paragraphs), ivars


def _join_summary(paragraphs: list[str]) -> str:
    """Joins leading paragraphs up to two paragraphs / ~60 characters."""
    selected: list[str] = []
    total = 0
    for paragraph in paragraphs:
        if paragraph.endswith(':'):
            break
        selected.append(paragraph)
        total += len(paragraph)
        if len(selected) >= 2 or total >= 60:
            break
    joined = ''
    for paragraph in selected:
        if joined and not joined.endswith(('.', '!', '?')):
            joined += '.'
        joined = f'{joined} {paragraph}'.strip()
    return joined


def model_summary(model_cls: Any) -> str:
    """Sanitized leading prose of a model or component class docstring.

    :param model_cls: class whose docstring is summarized
    :return: summary text, empty when the class has no usable docstring
    :rtype: str
    """
    try:
        return parse_docstring(getattr(model_cls, '__doc__', None))[0]
    except Exception:
        logger.debug('Summary extraction failed for %r', model_cls,
                     exc_info=True)
        return ''


def model_field_ivars(
        model_cls: type[pydantic.BaseModel]
) -> dict[str, str]:
    """``:ivar:`` documentation of a model's fields, MRO-outwards.

    Walks the MRO from the base classes to the class itself so the first
    entry found for a field wins in reading order: a subclass that
    re-documents an inherited field overrides the base-class phrasing.

    :param model_cls: pydantic model class
    :return: field name to sanitized documentation text
    :rtype: dict[str, str]
    """
    result: dict[str, str] = {}
    for base in reversed(getattr(model_cls, '__mro__', [model_cls])):
        ivars = parse_docstring(getattr(base, '__doc__', None))[1]
        result.update(ivars)
    return result


def _core_annotation(
        annotation: Any
) -> tuple[Any, bool]:
    """Unwraps ``X | None`` into its core type and an optional flag."""
    origin = typing.get_origin(annotation)
    if origin is typing.Union or origin is getattr(
            types, 'UnionType', None):
        args = list(typing.get_args(annotation))
        present = [arg for arg in args if arg is not type(None)]  # noqa: E711
        if len(present) != len(args):
            if len(present) == 1:
                return present[0], True
            return annotation, True
    return annotation, False


def _bounds_fact(field: pydantic.fields.FieldInfo) -> str | None:
    """Numeric bounds of a field's constraints (``0..65535``, ``>=1``)."""
    ge = gt = le = lt = None
    for meta in field.metadata:
        value = getattr(meta, 'ge', None)
        if value is not None:
            ge = value
            continue
        value = getattr(meta, 'gt', None)
        if value is not None:
            gt = value
            continue
        value = getattr(meta, 'le', None)
        if value is not None:
            le = value
            continue
        value = getattr(meta, 'lt', None)
        if value is not None:
            lt = value
    if ge is not None and le is not None and gt is None and lt is None:
        return f'{ge}..{le}'
    parts: list[str] = []
    if ge is not None:
        parts.append(f'>={ge}')
    if gt is not None:
        parts.append(f'>{gt}')
    if le is not None:
        parts.append(f'<={le}')
    if lt is not None:
        parts.append(f'<{lt}')
    return ', '.join(parts) or None


def field_facts(field: pydantic.fields.FieldInfo) -> list[str]:
    """Machine-checkable facts of one model field.

    Generated from the field itself, not hand-written, so they catch
    docstring rot: enum values, numeric bounds, ``optional`` for
    ``X | None`` annotations and ``REQUIRED`` for fields without a
    default.

    :param field: pydantic field info
    :type field: pydantic.fields.FieldInfo
    :return: fact strings in rendering order
    :rtype: list[str]
    """
    facts: list[str] = []
    core, optional = _core_annotation(field.annotation)
    if isinstance(core, type) and issubclass(core, enum.Enum):
        facts.append(
            'one of: ' + ', '.join(str(member.value) for member in core))
    bounds = _bounds_fact(field)
    if bounds:
        facts.append(bounds)
    if field.is_required():
        facts.append('REQUIRED — must be set')
    elif optional:
        facts.append('optional')
    return facts


def _field_comment(
        model_cls: type[pydantic.BaseModel],
        name: str,
        field: pydantic.fields.FieldInfo,
        ivars: dict[str, str]
) -> str:
    """Composed comment text of one field (prose + appended facts)."""
    prose = ''
    if field.description:
        prose = str(field.description)
    else:
        extra = field.json_schema_extra
        if isinstance(extra, dict) and 'comment' in extra:
            prose = str(extra['comment'])
    if not prose:
        prose = ivars.get(name, '')
    prose = sanitize_text(prose) if prose else ''
    facts = field_facts(field)
    prose_lower = prose.lower()
    new_facts = [fact for fact in facts if fact.lower() not in prose_lower]
    if prose and new_facts:
        prose = f"{prose} ({', '.join(new_facts)})"
    elif not prose and facts:
        prose = ', '.join(facts)
    if prose and (model_cls.__module__, model_cls.__qualname__,
                  name) in _SECRET_FIELDS:
        if not prose.endswith(('.', '!', '?')):
            prose += '.'
        prose = f'{prose} {_SECRET_WARNING}'
    return prose


def model_field_comments(
        model_cls: type[pydantic.BaseModel]
) -> dict[str, str]:
    """Comment text of every documented field of a configuration model.

    Precedence per field (first hit wins):
    :attr:`pydantic.Field.description` / ``json_schema_extra['comment']``
    (the third-party escape hatch), then ``:ivar:`` docstring entries
    (MRO-outwards, see :func:`model_field_ivars`), then generated facts
    only. Fields without any of these get no entry — filler is never
    invented.

    :param model_cls: pydantic model class
    :return: field name to comment text
    :rtype: dict[str, str]
    """
    try:
        ivars = model_field_ivars(model_cls)
        result: dict[str, str] = {}
        for name, field in model_cls.model_fields.items():
            text = _field_comment(model_cls, name, field, ivars)
            if text:
                result[name] = text
        return result
    except Exception:
        logger.debug('Field comment extraction failed for %r', model_cls,
                     exc_info=True)
        return {}


def component_comments(
        name: str,
        registry: dict[str, type[component.Component[Any]]],
        origins: dict[str, str]
) -> list[str]:
    """Header comment block of one ``components.<Name>`` entry.

    Combines the component class docstring summary (falling back to the
    configuration model summary) with the component's origin: built-in,
    programmatically registered or the distribution providing it, with
    the "off by default" note for extension components whose model
    default keeps ``on`` false.

    :param name: component name
    :type name: str
    :param registry: component registry (name to component class)
    :param origins: component origins (name to origin)
    :return: comment block strings (may be empty)
    :rtype: list[str]
    """
    try:
        factory = registry.get(name)
        if factory is None:
            return []
        origin = origins.get(name, 'registered')
        summary = model_summary(factory)
        model_cls = getattr(factory, 'config_model', None)
        if not summary and model_cls is not None:
            summary = model_summary(model_cls)
        default_off = True
        if model_cls is not None:
            on_field = getattr(model_cls, 'model_fields', {}).get('on')
            if on_field is not None and on_field.default is True:
                default_off = False
        if origin == 'built-in':
            origin_text = '(built-in)'
        elif origin == 'registered':
            origin_text = '(registered programmatically)'
        else:
            origin_text = f'(from {origin}, installed extension'
            origin_text += '; off by default)' if default_off else ')'
        return [f'{summary} {origin_text}'.strip()]
    except Exception:
        logger.debug('Component header extraction failed for %r', name,
                     exc_info=True)
        return []


def build_comment_map(
        conf: 'config.Config',
        registry: dict[str, type[component.Component[Any]]],
        origins: dict[str, str]
) -> dict[tuple[str, ...], list[str]]:
    """Maps YAML key paths to comment blocks for the whole document.

    Walks the same structures the dumper walked: the ``ae`` model (with
    nested models like ``tls``), the static ``log`` section and every
    ``components.<Name>`` entry with its actual model class from the
    registry, including dicts of nested models (``devices``). Each value
    is a list of paragraph strings the renderer wraps per insertion
    point.

    :param conf: configuration being serialized
    :type conf: config.Config
    :param registry: component registry (name to component class)
    :param origins: component origins (name to origin)
    :return: path tuple to comment blocks
    :rtype: dict[tuple[str, ...], list[str]]
    """
    comments: dict[tuple[str, ...], list[str]] = {}
    ae_summary = model_summary(type(conf.ae))
    if ae_summary:
        comments[('ae',)] = [ae_summary]
    _add_model_comments(comments, ('ae',), type(conf.ae), conf.ae)
    log_comment = _STATIC_COMMENTS.get(('log',))
    if log_comment:
        comments[('log',)] = [log_comment]
    extension_banner_done = False
    for name, entry in conf.components.items():
        path = ('components', name)
        origin = origins.get(name, 'registered')
        blocks: list[str] = []
        if (origin not in ('built-in', 'registered')
                and not extension_banner_done):
            blocks.append(EXTENSION_BANNER)
            extension_banner_done = True
        blocks.extend(component_comments(name, registry, origins))
        if blocks:
            comments[path] = blocks
        _add_model_comments(comments, path, type(entry), entry)
    return comments


def _add_model_comments(
        comments: dict[tuple[str, ...], list[str]],
        path: tuple[str, ...],
        model_cls: Any,
        instance: Any
) -> None:
    """Adds field comments of one model instance, recursing into nests."""
    try:
        for name, text in model_field_comments(model_cls).items():
            comments[path + (name,)] = [text]
        for name in getattr(model_cls, 'model_fields', {}):
            value = getattr(instance, name, None)
            if isinstance(value, pydantic.BaseModel):
                nested = path + (name,)
                summary = model_summary(type(value))
                if summary and nested not in comments:
                    comments[nested] = [summary]
                _add_model_comments(comments, nested, type(value), value)
            elif isinstance(value, dict):
                for key, item in value.items():
                    if (not isinstance(key, str)
                            or not isinstance(item, pydantic.BaseModel)):
                        continue
                    entry_path = path + (name, key)
                    summary = model_summary(type(item))
                    if summary:
                        comments.setdefault(entry_path, [summary])
                    _add_model_comments(
                        comments, entry_path, type(item), item)
    except Exception:
        logger.debug('Comment extraction failed at %r', path,
                     exc_info=True)


#: Block scalar headers (``|``, ``>-``, ``|2-``, ...)
_BLOCK_RE = re.compile(r'^[|>]([-+]?[0-9]*|[0-9]*[-+]?)$')

#: One mapping key line of the dumped document: indent, key (plain or
#: quoted) and the remainder of the line after the colon. The plain-key
#: branch never starts with ``-`` (sequence items), a quote (handled by
#: the first branches) or ``#``.
_KEY_RE = re.compile(
    r"^(?P<indent>[ ]*)"
    r"(?P<key>'[^']*'|\"[^\"]*\"|[^\s:#'\"-][^:#]*?)"
    r":[ \t]*(?P<value>.*)$")


def _unquote(key: str) -> str:
    """Plain text of a dumped YAML key (``'on'`` -> ``on``)."""
    if len(key) >= 2 and key[0] == key[-1] and key[0] in '\'"':
        inner = key[1:-1]
        if key[0] == "'":
            return inner.replace("''", "'")
        return inner.replace('\\"', '"').replace('\\\\', '\\')
    return key


def _quote_closed(value: str) -> bool:
    """Whether a scalar starting with a quote also closes on this line."""
    quote = value[0]
    index = 1
    total = len(value)
    while index < total:
        if value[index] == quote:
            if quote == "'":
                if index + 1 < total and value[index + 1] == "'":
                    index += 2
                    continue
                return True
            backslashes = 0
            probe = index - 1
            while probe >= 0 and value[probe] == '\\':
                backslashes += 1
                probe -= 1
            if backslashes % 2 == 0:
                return True
        index += 1
    return False


def _continuation_closes(line: str, quote: str) -> bool:
    """Whether a wrapped scalar's continuation line closes the quote."""
    stripped = line.rstrip()
    if not stripped:
        return False
    index = 0
    total = len(line)
    while index < total:
        if line[index] == quote:
            if quote == "'":
                if index + 1 < total and line[index + 1] == "'":
                    index += 2
                    continue
                return True
            backslashes = 0
            probe = index - 1
            while probe >= 0 and line[probe] == '\\':
                backslashes += 1
                probe -= 1
            if backslashes % 2 == 0:
                return True
        index += 1
    return False


def _emit_blocks(
        out: list[str], blocks: list[str], indent: int,
        blank_before: bool
) -> None:
    """Appends wrapped comment blocks to ``out``.

    Blocks are separated by blank lines; ``blank_before`` adds one above
    the whole group (section and component headers get breathing room,
    field comments stay tight against their key).
    """
    if blank_before and out and out[-1] != '':
        out.append('')
    width = max(30, COMMENT_WIDTH - indent - 2)
    for position, block in enumerate(blocks):
        if position and out and out[-1] != '':
            out.append('')
        for line in textwrap.wrap(block, width=width):
            out.append(' ' * indent + '# ' + line)


def _insert_comments(
        text: str,
        comments: dict[tuple[str, ...], list[str]]
) -> str:
    """Inserts comment lines above known key paths of dumped YAML.

    Scans the ``dump_yaml`` output line by line, tracking an
    indent-based path stack. Block scalars and wrapped quoted scalars
    are recognized and their bodies skipped, so their content is never
    mistaken for keys; value lines and sequence items are passed through
    untouched.
    """
    out: list[str] = []
    for line in textwrap.wrap(BANNER, width=COMMENT_WIDTH):
        out.append(f'# {line}')
    out.append('')
    stack: list[tuple[int, str]] = []
    skip_indent: int | None = None
    open_quote = ''
    for line in text.splitlines():
        if open_quote:
            out.append(line)
            if _continuation_closes(line, open_quote):
                open_quote = ''
            continue
        if skip_indent is not None:
            stripped = line.strip()
            if not stripped or len(line) - len(line.lstrip(' ')) \
                    > skip_indent:
                out.append(line)
                continue
            skip_indent = None
        match = _KEY_RE.match(line)
        if match is None or line.lstrip().startswith('#'):
            out.append(line)
            continue
        indent = len(match.group('indent'))
        key = _unquote(match.group('key'))
        value = match.group('value').strip()
        while stack and stack[-1][0] >= indent:
            stack.pop()
        path = tuple(entry_key for _, entry_key in stack) + (key,)
        blocks = comments.get(path)
        if blocks:
            blank_before = len(path) == 1 or (
                len(path) == 2 and path[0] == 'components')
            _emit_blocks(out, blocks, indent, blank_before)
        elif indent == 0 and out and out[-1] != '':
            # Keep top-level sections visually separated even when the
            # next one carries no comment of its own
            out.append('')
        out.append(line)
        if not value:
            stack.append((indent, key))
        elif _BLOCK_RE.match(value):
            skip_indent = indent
        elif value[0] in '\'"' and not _quote_closed(value):
            open_quote = value[0]
    return '\n'.join(out) + '\n'


def render_commented_yaml(
        conf: 'config.Config',
        text: str,
        registry: dict[str, type[component.Component[Any]]],
        origins: dict[str, str]
) -> str:
    """Inserts generated comments into a ``dump_yaml`` document.

    The result is verified to parse back into the same data as the
    input; on any mismatch (or any extraction failure) the plain text is
    returned unchanged, so a broken comment never corrupts a generated
    configuration.

    :param conf: configuration being serialized
    :param text: plain ``yaml.safe_dump`` output of the same config
    :param registry: component registry (name to component class)
    :param origins: component origins (name to origin)
    :return: commented YAML document
    :rtype: str
    """
    try:
        comments = build_comment_map(conf, registry, origins)
        rendered = _insert_comments(text, comments)
    except Exception:
        logger.warning(
            'Comment generation failed, writing the configuration '
            'without comments', exc_info=True
        )
        return text
    try:
        if yaml.safe_load(rendered) != yaml.safe_load(text):
            raise ValueError('commented YAML parses to different data')
    except Exception:
        logger.warning(
            'Commented YAML failed verification, writing the '
            'configuration without comments', exc_info=True
        )
        return text
    return rendered
